import { describe, it, expect } from "vitest";
import {
  classifyCloudFormationType,
  classifyTerraformType,
  detectIacFormat,
  extractReferences,
  importInfrastructure,
  parseCloudFormation,
  parseTerraform,
  scanHclBlocks,
  MAX_NODES,
} from "../src/iac-import.js";
import { toTerraform } from "../src/terraform-export.js";

/** Find an imported node by its display name. */
const node = (result, name) => result.nodes.find((item) => item.name === name);
/** True when a directed edge exists between two named nodes. */
const linked = (result, fromName, toName) => {
  const from = node(result, fromName);
  const to = node(result, toName);
  return result.connections.some((c) => c.from === from?.id && c.to === to?.id);
};

describe("format detection", () => {
  it("recognises Terraform, CloudFormation JSON, and YAML", () => {
    expect(detectIacFormat('resource "aws_s3_bucket" "b" {}')).toBe("terraform");
    expect(detectIacFormat('{"Resources":{"B":{"Type":"AWS::S3::Bucket"}}}')).toBe(
      "cloudformation-json"
    );
    expect(detectIacFormat("AWSTemplateFormatVersion: '2010-09-09'")).toBe("cloudformation-yaml");
  });

  it("returns null for unrelated text", () => {
    expect(detectIacFormat("just some prose")).toBe(null);
    expect(detectIacFormat("")).toBe(null);
  });

  it("explains that YAML templates need converting", () => {
    expect(() => importInfrastructure("AWSTemplateFormatVersion: '2010-09-09'")).toThrow(/YAML/);
  });

  it("refuses input it cannot identify", () => {
    expect(() => importInfrastructure("hello world")).toThrow(/Could not tell/);
  });
});

describe("HCL scanner", () => {
  it("keeps braces inside heredocs out of block matching", () => {
    const hcl = `
      resource "aws_iam_role" "app" {
        assume_role_policy = <<-EOT
          { "Version": "2012-10-17", "Statement": [{ "Effect": "Allow" }] }
        EOT
      }
      resource "aws_s3_bucket" "data" {
        bucket = "example"
      }
    `;
    const { blocks } = scanHclBlocks(hcl);
    expect(blocks.filter((b) => b.type === "resource")).toHaveLength(2);
    expect(blocks[1].labels).toEqual(["aws_s3_bucket", "data"]);
  });

  it("does not treat # inside a string as a comment", () => {
    const { blocks } = scanHclBlocks(
      'resource "aws_s3_bucket" "b" {\n  tags = { Name = "a#b" }\n}\nresource "aws_sqs_queue" "q" {}'
    );
    expect(blocks.filter((b) => b.type === "resource")).toHaveLength(2);
  });

  it("survives interpolation containing quotes and braces", () => {
    const { blocks } = scanHclBlocks(
      'resource "aws_lambda_function" "f" {\n  role = "${lookup(var.m, "key")}"\n}\nresource "aws_sqs_queue" "q" {}'
    );
    expect(blocks.filter((b) => b.type === "resource")).toHaveLength(2);
  });
});

describe("reference extraction", () => {
  it("tags each reference with its nearest attribute", () => {
    const refs = extractReferences('function_name = aws_lambda_function.api.arn\n  bucket = "x"');
    expect(refs).toEqual([{ attr: "function_name", target: "aws_lambda_function.api" }]);
  });

  it("ignores data-source lookups", () => {
    expect(extractReferences("vpc_id = data.aws_vpc.main.id")).toEqual([]);
  });

  it("finds references inside interpolated strings", () => {
    const refs = extractReferences('uri = "arn:aws:apigateway:${aws_lambda_function.api.arn}"');
    expect(refs[0].target).toBe("aws_lambda_function.api");
  });
});

describe("resource classification", () => {
  it("maps well-known types onto catalog services", () => {
    expect(classifyTerraformType("aws_lambda_function").service).toBe("AWS Lambda");
    expect(classifyTerraformType("aws_dynamodb_table").kind).toBe("data");
    expect(classifyCloudFormationType("AWS::SQS::Queue").service).toBe(
      "Amazon Simple Queue Service"
    );
  });

  it("treats plumbing as non-drawable", () => {
    expect(classifyTerraformType("aws_iam_role_policy_attachment")).toBe(null);
    expect(classifyTerraformType("aws_s3_bucket_versioning")).toBe(null);
    expect(classifyCloudFormationType("AWS::EC2::Subnet")).toBe(null);
  });

  it("falls back to the family for unlisted members", () => {
    expect(classifyTerraformType("aws_dynamodb_contributor_insights").service).toBe(
      "Amazon DynamoDB"
    );
  });
});

describe("Terraform import", () => {
  const stack = `
    # Checkout platform — generated by AWS Flow Studio
    provider "aws" {
      region = "eu-west-1"
    }

    resource "aws_apigatewayv2_api" "public" {
      name = "checkout"
      tags = { Name = "Checkout API", Environment = "Staging" }
    }

    resource "aws_apigatewayv2_integration" "lambda" {
      api_id = aws_apigatewayv2_api.public.id
      integration_uri = aws_lambda_function.checkout.invoke_arn
    }

    resource "aws_lambda_function" "checkout" {
      function_name = "checkout"
      tags = { Name = "Checkout handler" }
    }

    resource "aws_dynamodb_table" "orders" {
      name = "orders"
      tags = { Name = "Orders table" }
    }

    resource "aws_iam_role" "lambda_exec" {
      name = "lambda-exec"
      tags = { Name = "Lambda execution role" }
    }
  `;

  it("reads the region and title from the file", () => {
    const result = parseTerraform(stack);
    expect(result.region).toBe("eu-west-1");
    expect(result.name).toBe("Checkout platform");
    expect(result.format).toBe("terraform");
  });

  it("draws services and hides plumbing", () => {
    const result = parseTerraform(stack);
    const names = result.nodes.map((n) => n.name).sort();
    expect(names).toContain("Checkout API");
    expect(names).toContain("Checkout handler");
    expect(names).not.toContain("Lambda");
    expect(result.stats.plumbing).toBeGreaterThan(0);
  });

  it("traces api → lambda through the integration resource", () => {
    const result = parseTerraform(stack);
    expect(linked(result, "Checkout API", "Checkout handler")).toBe(true);
  });

  it("honours tags for name, environment, and criticality", () => {
    const result = parseTerraform(stack);
    expect(node(result, "Checkout API").environment).toBe("Staging");
    expect(node(result, "Orders table").criticality).toBe("high");
    expect(node(result, "Checkout handler").notes).toBe(
      "Imported from aws_lambda_function.checkout"
    );
  });

  it("falls back to a humanised resource name without tags", () => {
    const result = parseTerraform('resource "aws_sqs_queue" "order_events" {}');
    expect(result.nodes[0].name).toBe("Order events");
  });

  it("contracts a load balancer through listeners and target groups", () => {
    const result = parseTerraform(`
      resource "aws_lb" "edge" { name = "edge" tags = { Name = "Public ALB" } }
      resource "aws_lb_target_group" "app" { port = 443 }
      resource "aws_lb_listener" "https" {
        load_balancer_arn = aws_lb.edge.arn
        default_action { target_group_arn = aws_lb_target_group.app.arn }
      }
      resource "aws_lb_target_group_attachment" "app" {
        target_group_arn = aws_lb_target_group.app.arn
        target_id = aws_instance.web.id
      }
      resource "aws_instance" "web" { tags = { Name = "Web tier" } }
    `);
    expect(result.nodes).toHaveLength(2);
    expect(linked(result, "Public ALB", "Web tier")).toBe(true);
  });

  it("points a queue at the function it triggers", () => {
    const result = parseTerraform(`
      resource "aws_sqs_queue" "jobs" { tags = { Name = "Job queue" } }
      resource "aws_lambda_function" "worker" { tags = { Name = "Worker" } }
      resource "aws_lambda_event_source_mapping" "jobs" {
        event_source_arn = aws_sqs_queue.jobs.arn
        function_name = aws_lambda_function.worker.arn
      }
    `);
    expect(linked(result, "Job queue", "Worker")).toBe(true);
    expect(linked(result, "Worker", "Job queue")).toBe(false);
  });

  it("uses the target service to pick the connection type", () => {
    const result = parseTerraform(`
      resource "aws_lambda_function" "api" { environment { TABLE = aws_dynamodb_table.t.name } }
      resource "aws_dynamodb_table" "t" { name = "t" }
      resource "aws_cloudwatch_log_group" "logs" {
        name = aws_lambda_function.api.function_name
      }
    `);
    const toTable = result.connections.find((c) => c.to === node(result, "T")?.id);
    expect(toTable.type).toBe("data");
    expect(toTable.label).toBe("Query");
  });

  it("points telemetry from the workload at its log group", () => {
    const result = parseTerraform(`
      resource "aws_lambda_function" "api" { tags = { Name = "API" } }
      resource "aws_cloudwatch_log_group" "api" {
        name = "/aws/lambda/\${aws_lambda_function.api.function_name}"
        tags = { Name = "API logs" }
      }
    `);
    expect(linked(result, "API", "API logs")).toBe(true);
    expect(result.connections[0].type).toBe("telemetry");
  });

  it("calls delivery out of a queue an event, not a request", () => {
    const result = parseTerraform(`
      resource "aws_sqs_queue" "jobs" { tags = { Name = "Jobs" } }
      resource "aws_lambda_function" "worker" { tags = { Name = "Worker" } }
      resource "aws_lambda_event_source_mapping" "m" {
        event_source_arn = aws_sqs_queue.jobs.arn
        function_name = aws_lambda_function.worker.arn
      }
    `);
    expect(result.connections[0].type).toBe("event");
  });

  it("does not draw placement references as traffic", () => {
    const result = parseTerraform(`
      resource "aws_vpc" "main" { cidr_block = "10.0.0.0/16" tags = { Name = "Main VPC" } }
      resource "aws_subnet" "a" { vpc_id = aws_vpc.main.id }
      resource "aws_lb" "edge" {
        subnets = [aws_subnet.a.id]
        tags = { Name = "Edge" }
      }
    `);
    // The ALB lives in the VPC; it does not send traffic to it.
    expect(linked(result, "Edge", "Main VPC")).toBe(false);
    expect(result.connections).toHaveLength(0);
  });

  it("flags a plaintext listener as an unencrypted path", () => {
    const result = parseTerraform(`
      resource "aws_lb" "edge" { tags = { Name = "Edge" } }
      resource "aws_lb_listener" "plain" {
        load_balancer_arn = aws_lb.edge.arn
        protocol = "HTTP"
        default_action { target_group_arn = aws_lb_target_group.app.arn }
      }
      resource "aws_lb_target_group" "app" {}
      resource "aws_lb_target_group_attachment" "a" {
        target_group_arn = aws_lb_target_group.app.arn
        target_id = aws_instance.web.id
      }
      resource "aws_instance" "web" { tags = { Name = "Web" } }
    `);
    // The listener carries the plaintext signal, so the contracted edge inherits it.
    const edge = result.connections[0];
    expect(edge.encrypted).toBe(false);
    expect(edge.label).toBe("HTTP");
  });

  it("lays entry points out to the left of what they reach", () => {
    const result = parseTerraform(stack);
    expect(node(result, "Checkout API").x).toBeLessThan(node(result, "Checkout handler").x);
  });

  it("wraps a wide dependency level across columns instead of stacking it", () => {
    const result = parseTerraform(
      Array.from({ length: 9 }, (_, i) => `resource "aws_sqs_queue" "q${i}" {}`).join("\n")
    );
    // Nine unconnected services share one dependency level; they must not all
    // land on the same x or their labels collide.
    const columns = new Set(result.nodes.map((n) => n.x.toFixed(3)));
    expect(columns.size).toBe(3);
    expect(new Set(result.nodes.map((n) => `${n.x},${n.y}`)).size).toBe(9);
  });

  it("warns about modules, count/for_each, and other providers", () => {
    const result = parseTerraform(`
      module "network" { source = "./network" }
      resource "aws_lambda_function" "fan" {
        count = 3
        tags = { Name = "Fan" }
      }
      resource "google_storage_bucket" "gcs" { name = "x" }
    `);
    expect(result.warnings.join(" ")).toMatch(/Module "network"/);
    expect(result.warnings.join(" ")).toMatch(/count\/for_each/);
    expect(result.warnings.join(" ")).toMatch(/google/);
  });

  it("caps very large stacks and says so", () => {
    const many = Array.from(
      { length: MAX_NODES + 12 },
      (_, i) => `resource "aws_sqs_queue" "q${i}" {}`
    ).join("\n");
    const result = parseTerraform(many);
    expect(result.nodes).toHaveLength(MAX_NODES);
    expect(result.warnings.join(" ")).toMatch(new RegExp(`first ${MAX_NODES}`));
  });

  it("rejects empty and resource-free input", () => {
    expect(() => parseTerraform("")).toThrow(/Paste some Terraform/);
    expect(() => parseTerraform('variable "x" { default = 1 }')).toThrow(/No Terraform/);
  });
});

describe("round trip through the Terraform exporter", () => {
  const original = {
    name: "Serverless API",
    region: "ap-southeast-2",
    nodes: [
      {
        id: "n1",
        serviceName: "Amazon API Gateway",
        name: "Public API",
        environment: "Production",
        criticality: "high",
      },
      {
        id: "n2",
        serviceName: "AWS Lambda",
        name: "Handler",
        environment: "Staging",
        criticality: "medium",
      },
      {
        id: "n3",
        serviceName: "Amazon DynamoDB",
        name: "Orders",
        environment: "Production",
        criticality: "high",
      },
    ],
    connections: [
      { id: "c1", from: "n1", to: "n2", type: "request", encrypted: true },
      { id: "c2", from: "n2", to: "n3", type: "data", encrypted: false },
    ],
  };

  it("keeps services, metadata, and region", () => {
    const result = parseTerraform(toTerraform(original));
    expect(result.region).toBe("ap-southeast-2");
    expect(result.name).toBe("Serverless API");
    expect(result.nodes.map((n) => n.name).sort()).toEqual(["Handler", "Orders", "Public API"]);
    expect(node(result, "Handler").environment).toBe("Staging");
    expect(node(result, "Orders").criticality).toBe("high");
  });

  it("recovers the topology from the exported comments", () => {
    const result = parseTerraform(toTerraform(original));
    expect(linked(result, "Public API", "Handler")).toBe(true);
    expect(linked(result, "Handler", "Orders")).toBe(true);
    const dataEdge = result.connections.find((c) => c.to === node(result, "Orders").id);
    expect(dataEdge.encrypted).toBe(false);
  });

  it("restores external AI nodes exported as null_resource stubs", () => {
    const withAi = {
      ...original,
      nodes: [...original.nodes, { id: "n4", serviceName: "Claude", name: "Claude — reasoning" }],
      connections: [...original.connections, { id: "c3", from: "n2", to: "n4", type: "request" }],
    };
    const result = parseTerraform(toTerraform(withAi));
    const claude = node(result, "Claude — reasoning");
    expect(claude).toBeTruthy();
    expect(claude.serviceName).toBe("Claude");
    expect(linked(result, "Handler", "Claude — reasoning")).toBe(true);
  });
});

describe("CloudFormation import", () => {
  const template = {
    Description: "Event pipeline",
    Resources: {
      Bucket: {
        Type: "AWS::S3::Bucket",
        Properties: { Tags: [{ Key: "Name", Value: "Landing" }] },
      },
      Queue: { Type: "AWS::SQS::Queue", Properties: {} },
      Fn: {
        Type: "AWS::Lambda::Function",
        Properties: {
          Environment: { Variables: { BUCKET: { Ref: "Bucket" } } },
          Role: { "Fn::GetAtt": ["Role", "Arn"] },
        },
      },
      Role: { Type: "AWS::IAM::Role", Properties: {} },
      Mapping: {
        Type: "AWS::Lambda::EventSourceMapping",
        Properties: {
          EventSourceArn: { "Fn::GetAtt": ["Queue", "Arn"] },
          FunctionName: { Ref: "Fn" },
        },
      },
      Subnet: { Type: "AWS::EC2::Subnet", Properties: {} },
    },
  };

  it("draws services and skips plumbing", () => {
    const result = parseCloudFormation(JSON.stringify(template));
    expect(result.format).toBe("cloudformation");
    expect(result.name).toBe("Event pipeline");
    const names = result.nodes.map((n) => n.name).sort();
    expect(names).toEqual(["Fn", "Landing", "Queue", "Role"]);
  });

  it("follows Ref, GetAtt, and event source mappings", () => {
    const result = parseCloudFormation(JSON.stringify(template));
    expect(linked(result, "Fn", "Landing")).toBe(true);
    expect(linked(result, "Queue", "Fn")).toBe(true);
  });

  it("resolves Fn::Sub references", () => {
    const result = parseCloudFormation(
      JSON.stringify({
        Resources: {
          Table: { Type: "AWS::DynamoDB::Table", Properties: {} },
          Fn: {
            Type: "AWS::Lambda::Function",
            Properties: { Environment: { Arn: { "Fn::Sub": "arn:aws:x:${Table}" } } },
          },
        },
      })
    );
    expect(linked(result, "Fn", "Table")).toBe(true);
  });

  it("honours DependsOn and reports conditional resources", () => {
    const result = parseCloudFormation(
      JSON.stringify({
        Resources: {
          Queue: { Type: "AWS::SQS::Queue", Properties: {}, Condition: "IsProd" },
          Fn: { Type: "AWS::Lambda::Function", Properties: {}, DependsOn: "Queue" },
        },
      })
    );
    expect(linked(result, "Fn", "Queue")).toBe(true);
    expect(result.warnings.join(" ")).toMatch(/conditional/);
  });

  it("rejects malformed templates with a readable message", () => {
    expect(() => parseCloudFormation("{ nope")).toThrow(/not valid JSON/);
    expect(() => parseCloudFormation("{}")).toThrow(/Resources/);
    expect(() => parseCloudFormation('{"Resources":{}}')).toThrow(/no AWS resources|Resources/i);
  });
});

describe("importInfrastructure", () => {
  it("dispatches on the detected dialect", () => {
    expect(importInfrastructure('resource "aws_sqs_queue" "q" {}').format).toBe("terraform");
    expect(
      importInfrastructure('{"Resources":{"Q":{"Type":"AWS::SQS::Queue","Properties":{}}}}').format
    ).toBe("cloudformation");
  });

  it("produces nodes shaped for the Flow Studio canvas", () => {
    const result = importInfrastructure('resource "aws_sqs_queue" "jobs" {}');
    expect(result.nodes[0]).toMatchObject({
      serviceName: "Amazon Simple Queue Service",
      environment: "Production",
    });
    expect(result.nodes[0].x).toBeGreaterThan(0);
    expect(result.nodes[0].y).toBeGreaterThan(0);
    expect(result.nodes[0]).not.toHaveProperty("kind");
  });
});
