/**
 * Terraform export — turn a Flow Studio architecture into a `main.tf` skeleton.
 *
 * Every canvas node maps to its closest Terraform resource type with a
 * ready-to-edit stub (names, tags, and TODOs); connections become a commented
 * topology section. The output is a starting point for real IaC, not a
 * deployable stack — external AI services render as SaaS placeholders.
 */

const RESOURCE_MAP = [
  { match: ["cloudfront"], type: "aws_cloudfront_distribution" },
  { match: ["lambda"], type: "aws_lambda_function" },
  { match: ["dynamodb"], type: "aws_dynamodb_table" },
  { match: ["aurora", "rds"], type: "aws_rds_cluster" },
  { match: ["eks", "kubernetes"], type: "aws_eks_cluster" },
  { match: ["ec2", "auto scaling"], type: "aws_autoscaling_group" },
  { match: ["api gateway"], type: "aws_apigatewayv2_api" },
  { match: ["s3", "storage service"], type: "aws_s3_bucket" },
  { match: ["sqs", "queue"], type: "aws_sqs_queue" },
  { match: ["sns"], type: "aws_sns_topic" },
  { match: ["eventbridge"], type: "aws_cloudwatch_event_bus" },
  { match: ["step functions"], type: "aws_sfn_state_machine" },
  { match: ["cognito"], type: "aws_cognito_user_pool" },
  { match: ["waf"], type: "aws_wafv2_web_acl" },
  { match: ["shield"], type: "aws_shield_protection" },
  { match: ["route 53", "dns"], type: "aws_route53_zone" },
  { match: ["cloudwatch"], type: "aws_cloudwatch_dashboard" },
  { match: ["load balancing", "elb", "alb"], type: "aws_lb" },
  { match: ["backup"], type: "aws_backup_vault" },
  { match: ["kinesis"], type: "aws_kinesis_stream" },
  { match: ["opensearch", "elasticsearch"], type: "aws_opensearch_domain" },
  { match: ["iam", "identity and access"], type: "aws_iam_role" },
];

const SAAS_MATCH = [
  "claude",
  "chatgpt",
  "foundation model",
  "ai agent",
  "vector database",
  "embeddings",
  "guardrails",
];

/** Terraform-safe identifier from a display name. */
export function tfName(value, taken = new Set()) {
  let base = String(value || "service")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .replace(/^(\d)/, "_$1");
  if (!base) base = "service";
  let name = base;
  let i = 2;
  while (taken.has(name)) name = `${base}_${i++}`;
  taken.add(name);
  return name;
}

function resourceFor(node) {
  const hay = `${node?.serviceName || ""} ${node?.name || ""}`.toLowerCase();
  if (SAAS_MATCH.some((m) => hay.includes(m))) return null;
  const hit = RESOURCE_MAP.find((r) => r.match.some((m) => hay.includes(m)));
  return hit ? hit.type : "aws_cloudformation_stack";
}

/**
 * Render a Flow Studio state ({name, region, nodes, connections}) as main.tf.
 * @returns {string}
 */
export function toTerraform(state = {}) {
  const nodes = state.nodes || [];
  const taken = new Set();
  const names = new Map();
  const out = [];

  out.push(`# ${state.name || "Architecture"} — generated by AWS Flow Studio`);
  out.push(`# Skeleton only: review every TODO before applying.`);
  out.push("");
  out.push(`terraform {`);
  out.push(`  required_providers {`);
  out.push(`    aws = { source = "hashicorp/aws", version = ">= 5.0" }`);
  out.push(`  }`);
  out.push(`}`);
  out.push("");
  out.push(`provider "aws" {`);
  out.push(`  region = "${state.region || "us-east-1"}"`);
  out.push(`}`);

  for (const node of nodes) {
    const name = tfName(node.name || node.serviceName, taken);
    names.set(node.id, name);
    const type = resourceFor(node);
    out.push("");
    if (!type) {
      out.push(`# "${node.name}" is an external AI/SaaS dependency (${node.serviceName}).`);
      out.push(`# Configure its API key via a secret manager; no AWS resource is created.`);
      out.push(`resource "null_resource" "${name}" {`);
      out.push(`  # TODO: wire ${node.name} credentials + endpoint`);
      out.push(`}`);
      continue;
    }
    out.push(`resource "${type}" "${name}" {`);
    out.push(`  # TODO: configure ${node.name} (${node.serviceName})`);
    out.push(`  tags = {`);
    out.push(`    Name        = "${node.name}"`);
    out.push(`    Environment = "${node.environment || "Production"}"`);
    out.push(`    Criticality = "${node.criticality || "medium"}"`);
    out.push(`  }`);
    out.push(`}`);
  }

  const connections = state.connections || [];
  if (connections.length) {
    out.push("");
    out.push(`# --- Topology (from the canvas) ---`);
    for (const c of connections) {
      const from = names.get(c.from) || c.from;
      const to = names.get(c.to) || c.to;
      const enc = c.encrypted === false ? " (UNENCRYPTED!)" : "";
      out.push(`# ${from} --${c.type || "request"}--> ${to}${enc}`);
    }
  }

  out.push("");
  return out.join("\n");
}
